name: osusume_app
description: "Osusume! – Your Japan dining assistant."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.0.0

  # State management
  flutter_riverpod: ^2.5.1

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CherryBombOne
      fonts:
        - asset: assets/fonts/CherryBombOne-Regular.ttf
